# Generated by Django 4.2.5 on 2024-09-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
