# Generated by Django 4.2.5 on 2024-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_rename_create_at_wallet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
