# Generated by Django 4.2.5 on 2024-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_wallet_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
