services:
  
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      -  "8080:80"      # Expose Nginx on port 80
    volumes:
      - ./Backend/staticfiles:/app/staticfiles  # Serve static files
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
    depends_on:
      - django  # Wait for Django to be ready



  db:
    image: postgres:16  # Use the latest PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8086
      POSTGRES_DB: doctor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:  
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Optional if your Dockerfile is named 'Dockerfile'
    image: doctor-find-backend-django  # Add this line for a valid image name
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    depends_on:
      - db  # Ensure that the db service is started before django
    env_file:
      - .env
    environment:
      - POSTGRES_DB=doctor  # Database name
      - POSTGRES_USER=postgres  # Database user
      - POSTGRES_PASSWORD=8086  # Database password
      - DB_HOST=db  # Host name for the database
      - DB_PORT=5432  # Port for the database
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000 --workers 3

volumes:
  postgres_data:  # Use a named volume for PostgreSQL data

