# Generated by Django 4.2.5 on 2024-09-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0035_remove_transaction_razorpay_payment_id_and_more'),
        ('Chat', '0006_alter_chatroom_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctorprofile'),
        ),
    ]
