# Generated by Django 4.2.5 on 2024-08-31 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0026_remove_doctorprofile_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='Doctors.slots'),
        ),
    ]
