# Generated by Django 4.2.5 on 2024-08-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0027_alter_bookings_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctors.slots'),
        ),
    ]
