# Generated by Django 4.2.5 on 2024-08-31 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0030_remove_bookings_slots_bookings_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Doctors.slots'),
        ),
    ]
