# Generated by Django 4.2.5 on 2024-09-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0034_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
