# Generated by Django 4.2.5 on 2024-09-30 01:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0035_remove_transaction_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
