# Generated by Django 4.2.5 on 2024-09-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0036_slots_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
