# Generated by Django 4.2.5 on 2024-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0038_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
