# Generated by Django 4.2.5 on 2024-10-07 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0040_remove_doctorprofile_notifications_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='doctor',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            # Set the default to a valid user ID (for example, 1)
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
