# Generated by Django 4.2.5 on 2024-10-08 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_recipient(apps, schema_editor):
    Notification = apps.get_model('Doctors', 'Notification')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Specify a default recipient user ID here
    default_recipient_id = 51 # Change this to the actual user ID you want to use

    # Update existing notifications to set the default recipient
    Notification.objects.filter(recipient=None).update(recipient_id=default_recipient_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0043_remove_notification_doctor_notification_recipient'),
    ]

    operations = [
        migrations.RunPython(set_default_recipient),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
